apiVersion: v1
kind: ConfigMap
metadata:
  name: clinicalrag-config
  namespace: default
data:
  OLLAMA_URL: "http://ollama-service:11434"
  QDRANT_URL: "http://qdrant-service:6333"
  COLLECTION_NAME: "clinical_docs"
  EMBEDDING_MODEL: "nomic-embed-text"
  LLM_MODEL: "mistral"
  EMBEDDING_SIZE: "768"